app:
  mongodb:
    user: ${env.MONGODB_EVENT_STORE_USER}
    password: ${env.MONGODB_EVENT_STORE_PASSWORD}
    database: posts-query-db

spring:
  data:
    mongodb:
      uri: mongodb+srv://${app.mongodb.user}:${app.mongodb.password}@clustertest.dcm8a.mongodb.net/${app.mongodb.database}?retryWrites=true&w=majority

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    enabled: false
  kafka:
    clientid: posts-query-app
    consumer:
      bootstrap-servers: ${app.kafka.broker.host}:${app.kafka.broker.port}
      event-processor-mode: tracking
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
    properties:
      security.protocol: PLAINTEXT