server:
  port: 8888

app:
  config:
    user: blabla-user
    password: blabla-password
  kafka:
    broker:
      host: test
      port: 9092
    api:
      key: test
      secret: test

spring:
  profiles:
    active: default
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/test
          username: test
          password: secret_key

    bus:
      enabled: true
      refresh:
        enabled: true
      trace:
        enabled: true
  kafka:
    bootstrap-servers: ${app.kafka.broker.host}:${app.kafka.broker.port}
    properties:
      security.protocol: SASL_SSL
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='${app.kafka.api.key}'   password='${app.kafka.api.secret}';
        mechanism: PLAIN
      ssl:
        endpoint.identification.algorithm: https
      session.timeout.ms: 45000

# Logging
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    config:
      server.encrypt.enabled: true

server.port: 8080
